---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: inventory
  namespace: dev
spec:
  destination:
    name: inventory
    namespace: dev
  sources:
    - name: order
      namespace: dev
      action: allow

