apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: sit
  labels:
    app: order
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: order
# ---
# apiVersion: consul.hashicorp.com/v1alpha1
# kind: ServiceDefaults
# metadata:
#   name: order
#   namespace: sit
# spec:
#   protocol: "http"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: order
  namespace: sit
automountServiceAccountToken: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-v1
  namespace: sit
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/transparent-proxy: "true"
        consul.hashicorp.com/service-meta-version: "sit"
        consul.hashicorp.com/service-tags: "sit"
        k8s.v1.cni.cncf.io/networks: '[{"name":"consul-cni"}]'
    spec:
      serviceAccountName: order
      containers:
        - name: order
          image: muarwi/order-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          env:
            - name: APP_API_VERSION
              value: sit
            - name: SPRING_HTTP_CLIENT_SERVICE_GROUP_INVENTORY_BASEURL
              value: http://inventory.virtual.inventory.ns.consul:8081
            # - name: SERVER_TOMCAT_ACCESSLOG_ENABLED
            #   value: "true"
            # - name: SERVER_TOMCAT_ACCESSLOG_DIRECTORY
            #   value: /dev 
            # - name: SERVER_TOMCAT_ACCESSLOG_PREFIX
            #   value: stdout 
            # - name: SERVER_TOMCAT_ACCESSLOG_BUFFERED
            #   value: "false"
