---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: inventory
  namespace: inventory1
spec:
  destination:
    name: inventory
    namespace: inventory1
  sources:
    - name: order
      namespace: order
      action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: inventory
  namespace: inventory2
spec:
  destination:
    name: inventory
    namespace: inventory2
  sources:
    - name: order
      namespace: order
      action: allow
---