apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceResolver
metadata:
  name: order
  namespace: order
spec:
  defaultSubset: v1
  subsets:
    v1:
      filter: 'Service.Meta.version == v1'
    v2:
      filter: 'Service.Meta.version == v2'