apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: order
  labels:
    app: order
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: order
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: order
  namespace: order
spec:
  protocol: "http"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: order
  namespace: order
automountServiceAccountToken: true
---
